#ifndef __STUDY_CPP_VERSION_H__
#define __STUDY_CPP_VERSION_H__

#define STUDY_CPP_VER_MAJOR 1
#define STUDY_CPP_VER_MINOR 0
#define STUDY_CPP_VER_PATCH 0

#define STUDY_CPP_VERSION (STUDY_CPP_VER_MAJOR * 10000 + STUDY_CPP_VER_MINOR * 100 + STUDY_CPP_VER_PATCH)

#endif  // __STUDY_CPP_VERSION_H__
